### ISSUE TITLE
How is it going?

### ISSUE THREAD

**Issue by ErikOrjehag** [DarrenLevine/TipTap#1]
Did you make any progress with the control algoritm from your last Youtube video? I find this project very interesting and would like to explore something similar 🙂

**Comment by DarrenLevine** [comment]
Not much progress recently, mostly due to lack of free time, and technical hurdles. The two technical issues I've been working to overcome are 1) the calculations for non-dimensionally reduced models are very expensive and so it's hard to make high rate controllers when trying to take into account the full dynamics in the math 2) the uart connection to the motors are daisy chained in a way that again limits the controller's bandwidth. So, I've been experimenting with developing a lower bandwidth controller (which can be done... here is an example of a very low rate controller that still has high performance https://github.com/DarrenLevine/rigmech/blob/master/example_ControlledPendulum.gif). An alternative would be to move to a higher rate CAN bus motor controller such as the moteus controller, and work to dimensionally reduce my model.
